# Introduction to Numpy 
---

Numpy is a Python module that is primarily used for scientific computations in various fields such as physics, mathematics, and engineering. 

Its key feature is the N-dimensional array object, which makes it possible to work with arrays and matrices of different dimensions. This functionality is crucial for scientific and numerical computations.

In addition to N-dimensional arrays, Numpy also provides a wide range of tools for performing linear algebra operations, matrix manipulation, and statistical analysis. It also includes a random number generator that can be used to create arrays of random numbers, making it an essential tool for many scientific simulations and experiments.

In [2]:
import numpy as np

An empty vector and an empty matrix are constructed initially.

In [3]:
zero_vector = np.zeros(7)

zero_vector

array([0., 0., 0., 0., 0., 0., 0.])

A two-dimensional array can be defined in Numpy by providing a tuple as an argument.

The tuple provided as argument specifies two things:

* The first argument is the number of rows in the matrix
* The second argument is the number of columns in the matrix.

So, if the tuple (2,3) is provided as input, the result is a matrix consisting of 2 rows and 3 columns.

In [4]:
zero_matrix = np.zeros((2,3))

print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
one_vector = np.ones(3)

one_vector

array([1., 1., 1.])

In [7]:
one_matrix = np.ones((5,7))

one_matrix

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

NumPy arrays can be constructed using specific values by making use of the `np.array` function. This function takes a sequence of numbers, which is typically a list of numbers, as its input argument. 

**It is important to note that in the subsequent discussions, vectors are represented using lowercase variables, while matrices are represented using uppercase variables.**

In [8]:
x = np.array([1,2,3])
y = np.array([2,4,6])

print(x,y)

[1 2 3] [2 4 6]


When a two-dimensional NumPy array is constructed, the elements of each row are specified as a list. 

The entire matrix can then be defined as a list of list, which contains each of the list of the row elements.

In [15]:
A = np.array([[11,22],[55,77]])

print(A)

[[11 22]
 [55 77]]


NumPy also contains methods that help in taking the transpose of a matrix.

The tranpose of a matrix is an operation performed on the matrix in which the rows and columns are interchanged.

To put it differently, the elements in the first row of the original matrix become the elements of the first column in the transposed matrix, and so forth for the other rows.

In [22]:
transA = A.transpose()

print("A:\n",A)
print("\nTranspose of A:\n",transA)

A:
 [[11 22]
 [55 77]]

Transpose of A:
 [[11 55]
 [22 77]]


---

### Slicing Numpy Array    

NumPy arrays can easily be indexed, regardless of their dimensions.

When using NumPy arrays as vectors, individual elements can be accessed using their index positions. It is important to note that indices in NumPy arrays start from 0.

With matrices, the first index specifies the row of the array and the second index specifies the column of the array.

Numpy arrays can also be sliced using proper indexing. The start index is included but the stop index is not.


In [7]:
x1 = np.array([1,2,3])
y1 = np.array([2,4,6])

X1 = np.array([[1,2,3],[4,5,6]])
Y1 = np.array([[2,4,6],[8,10,12]])

In [8]:
x1[2]

3

Two elements of vector `y1` with index 0 and 1 can be obtained by slicing the vector using 0 as the starting index and 2 as the stopping index.

In [9]:
y1[0:2]

array([2, 4])

Given two vectors `x1` and `y1` containing three elements each, element-wise addition can be performed by adding corresponding elements of each vector. The result of this operation can be stored in a new vector `z`.

In [11]:
z = x1 + y1

print(z)

[3 6 9]


The above syntax gives access to the first column of matrix `X1`.

In [12]:
X1[:,1]

array([2, 5])

The similar operation can be performed on matrix `Y1`.

In [13]:
Y1[:,0]

array([2, 8])

The first column of matrix `X1` can be added with `Y1` by using the addition operator. The result of this addition can then be assigned to a matrix named `Z`. The elements of `Z` will be element-wise additions of the corresponding elements from the first column of `X1` and `Y1`.

In [14]:
Z = X1[:,1] + Y1[:,1]

print(Z)

[ 6 15]


By indexing the row number and using colon as an index for column, the first row of matrix `X1` can be accessed.

In [15]:
X1[0,:]

array([1, 2, 3])

Alternatively, since matrices are defined as nested lists, a shorthand can also be used to obtain similar result. 

The second row of matrix `Y1` is sliced out by simply indexing using the row number.

In [16]:
Y1[1]

array([ 8, 10, 12])

---

### Indexing Numpy Arrays


NumPy arrays can be indexed using other arrays or sequence-like objects like lists in addition to indexing with integers. This feature allows for more complex operations to be performed on NumPy arrays. 

One can use boolean indexing to get specific elements in an array or use fancy indexing to select a subset of an array. It's also possible to use arithmetic operations and comparison operators to index NumPy arrays. 

The resulting index can be used to access elements in the original array or to assign new values to those elements.

In [17]:
z1 = np.array([1,3,5,7,9])

print(z1)

[1 3 5 7 9]


A new vector `z2` can be defined by adding 1 to each element of vector `z1`.

In [41]:
z2 = z1 + 1

print(z2)

[ 2  4  6  8 10]


A list containing the indices used to index `z1` and `z2` is created below.

In [43]:
ind = [0,2,3]

print(z1[ind])

[1 5 7]


Using a NumPy array to index other arrays involves creating an index array, where the elements of the index array correspond to the indices of the elements in the other arrays that we want to extract. We can then use this index array to extract the desired elements from the other arrays.

In [46]:
ind = np.array(ind)
print(type(ind))

print(z2[ind])

<class 'numpy.ndarray'>
[2 6 8]


It is also possible to use logical indices to index NumPy arrays. The logical indices are essentially arrays of Boolean values, where `True` and `False` represent the elements that should and should not be included in the indexed array, respectively.

In [47]:
z1 > 6

array([False, False, False,  True,  True])

The first three elements of the vector z1 are determined to be less than 6. Consequently, a Boolean array is generated with its first three elements being `False`.

The fourth and fifth elements of the Boolean array are `True`, which correspond to the fourth and fifth elements in the vector z1 that are greater than 6.

In [49]:
print(z2)

z2[z2 >= 6]

[ 2  4  6  8 10]


array([ 6,  8, 10])

Python returns those elements of the array for which the corresponding value in the Boolean array is **True**.

---

#### Subtle distinction between Slicing and Indexing

When an array is sliced using the colon operator, a view of the object is obtained, allowing for modification of the slice which in turn modifies the original array. 



In contrast, when an array is indexed, a copy of the original array is returned.

In [21]:
print("Vector z1:\n",z1)

w = z1[0:3]

print("Vector w after slicing:\n",w)

w[0] = 100

print("\n\nAfter reinitializing w\n")
print("Vector w:\n",w)
print("Vector z1:\n",z1)

Vector z1:
 [100   3   5   7   9]
Vector w after slicing:
 [100   3   5]


After reinitializing w

Vector w:
 [100   3   5]
Vector z1:
 [100   3   5   7   9]


A new vector, `w`, is created by slicing the first elements of `z1`.

Modifying the first element in `w` to a value of 100 will also change the first element in the vector `z1`.

In [23]:
z1 = np.array([1,3,5,7,9])

ind_vector = [0,1,2]

w1 = z1[ind_vector]

print("Vector z1:\n",z1)
print("Vector w1 after indexing:\n",w1)

w1[0] = 250

print("\n\nAfter reintializing w1\n")
print("Vector z1:\n",z1)
print("Vector w1:\n",w1)


Vector z1:
 [1 3 5 7 9]
Vector w1 after indexing:
 [1 3 5]


After reintializing w1

Vector z1:
 [1 3 5 7 9]
Vector w1:
 [250   3   5]


By using indexing, it is possible to observe that the first element of vector `w1` has been altered while the first element of vector `z1` remains unchanged.

---

### Building and Examining NumPy Arrays
    
Numpy provides a couple of ways to construct arrays with fixed start and end values, such that the other elements are uniformly spaced between them.

The first way involves using the numpy `linspace` function.

The numpy function, linspace, takes three arguments when called: the starting point, the ending point (which will be included in the resulting array), and the number of elements to be generated in the array.

In [3]:
first_array = np.linspace(0,100,10)

print(first_array)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In addition to linspace, NumPy provides another function called `logspace` that creates an array of elements that are logarithmically spaced.

To create an array of ten logarithmically spaced elements between 250 and 500, we first need to take the base 10 logarithm of 250 and 500. The logarithmic values can then be passed as arguments to the `logspace` function.

In [4]:
start_val = np.log10(250)
finish_val = np.log10(500)

print("Log10 of 250: {}\nLog10 of 500: {}".format(start_val,finish_val))

Log10 of 250: 2.3979400086720375
Log10 of 500: 2.6989700043360187


In [5]:
second_array = np.logspace(start_val,finish_val,10)

print(second_array)

[250.         270.01493472 291.63225989 314.98026247 340.19750004
 367.43362307 396.85026299 428.62199143 462.93735614 500.        ]


The shape of an array can be determined by accessing the shape attribute of the array object. 

For example, if an array object is defined with 2 rows and 4 columns, the shape attribute would return the tuple (2,4).

In [6]:
B = np.array([[1,2,3,4],[10,11,12,13]])

print(B.shape)

print("\nMatrix B has {} rows and {} columns".format(B.shape[0],B.shape[1]))

(2, 4)

Matrix B has 2 rows and 4 columns


When the `size` attribute is called on an array object, it returns the total number of elements in the array. This can be used to confirm that the multiplication of the rows and columns of the shape attribute equals the number of elements in the array.

In [7]:
print("Matrix B contains {} elements".format(B.size))

Matrix B contains 8 elements


In array manipulation, it is common to encounter scenarios where it is necessary to verify whether any or all elements of an array meet a particular logical condition.


Generating a small vector to check two things:

- First, if any of its entries are greater than 0.9
- Second, if all of its entries are greater than or equal to 0.1

A vector is created by generating 10 random numbers drawn from the standard uniform distribution.

In [13]:
vector1 = np.random.random(10)

The `any` method can be used to check if any of the elements in an array satisfy a logical condition.

In [14]:
if np.any(vector1 > 0.9):
    print("Vector with an element greater than 0.9: {}".format(np.any(vector1>0.9)))

else:
    print("Vector with an element greater than 0.9: {}".format(np.any(vector1>0.9)))

Vector with an element greater than 0.9: True


The numpy method `all` can be utilized to check if all the elements of an array fulfill a logical condition.

In [15]:
if np.all(vector1 >= 0.1):
    print("Vector with all elements greater than or equal 0.1: {}".format(np.all(vector1>=0.1)))
else:
    print("Vector with all elements greater than or equal 0.1: {}".format(np.all(vector1>=0.1)))

Vector with all elements greater than or equal 0.1: True


As the vector generated is relatively small, one can print the vector and check if the conditions are met.

In [16]:
print(vector1)

[0.93557858 0.68188266 0.46739248 0.6135025  0.80004963 0.20660151
 0.77719938 0.62235582 0.50057327 0.12788521]


The function produces a scalar output of either `True` or `False` for the entire array instead of a logical array.